StocksScreener/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from schema_graph.views import Schema

admin.autodiscover()

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("users/api/v1/", include("users.api_urls", namespace="users_api")),
    path("market/", include("market.urls", namespace="market")),
    path("market/api/v1/", include("market.api_urls", namespace="market_api")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("egx/", include("egx.urls", namespace="egx")),
    path("crypto/", include("crypto.urls", namespace="crypto")),
    path("forex/", include("forex.urls", namespace="forex")),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("StocksScreener.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

urlpatterns += [
    path("schema/", Schema.as_view()),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
######################################################################
admin.site.site_header = "Stocks-Screener"
admin.site.site_title = "Stocks Screener"
admin.site.index_title = "Stocks Screener Admin"
#######################################################################

egx/urls.py
from django.urls import path

from egx.views import home, companies

app_name = "egx"

urlpatterns = [
    path('', home, name='home'),
    path('companies', companies, name='companies'),
]

market/urls.py
from django.urls import path

from market.views import *

app_name = "market"

urlpatterns = [
    path('list', list_stocks, name='list_stocks'),
    path('create', create_stock, name='create_stock'),
    path('update/<int:pk>', update_stock, name='update_stock'),
    path('delete/<int:pk>', delete_stock, name='delete_stock'),
    path('<int:pk>', view_stock, name='view_stock'),

    path('stock_weekly/<int:pk>', view_stock_weekly, name='view_stock_weekly'),
    path('stock_monthly/<int:pk>', view_stock_monthly, name='view_stock_monthly'),

    path('sectors', sectors, name='sectors'),

]

market/models.py
from django.db.models import *
from django.db.models import QuerySet
from django.urls import reverse
from django.utils import timezone


################################ --- Soft Deletion --- ##########################################

# SoftDeletionQuerySet Model

class SoftDeletionQuerySet(QuerySet):
    @property
    def delete(self):
        return super(SoftDeletionQuerySet, self).update(time_deleted=timezone.now(), deleted=True)

    def hard_delete(self):
        return super(SoftDeletionQuerySet, self).delete()

    def alive(self):
        return self.filter(time_deteted=None)

    def dead(self):
        return self.exclude(time_deteted=None)


# SoftDeletionManager Model
class SoftDeletionManager(Manager):
    def __init__(self, *args, **kwargs):
        self.alive_only = kwargs.pop('alive_only', True)
        super(SoftDeletionManager, self).__init__(*args, **kwargs)

    def get_queryset(self):
        if self.alive_only:
            return SoftDeletionQuerySet(self.model).filter(time_deleted=None)
        return SoftDeletionQuerySet(self.model)

    def hard_delete(self):
        return self.get_queryset().hard_delete()


## SoftDeletion Model
class SoftDeletionModel(Model):
    time_deleted = DateTimeField(db_column='TimeDeleted', blank=True, null=True)
    deleted = BooleanField(db_column='Deleted', blank=True, null=True, default=False)

    objects = SoftDeletionManager()
    all_objects = SoftDeletionManager(alive_only=False)

    class Meta:
        abstract = True

    def delete(self):
        self.time_deleted = timezone.now()
        self.deleted = True
        self.save()

    def hard_delete(self):
        super(SoftDeletionModel, self).delete()


######################################################################################################
class Stock(SoftDeletionModel):

    symbol = CharField(db_column='Symbol', max_length=10, db_index=True, unique=True)
    name = CharField(db_column='Name', max_length=100, db_index=True)
    sector = CharField(db_column='Sector', max_length=45, blank=True, null=True)

    info = TextField(db_column='Info', blank=True, null=True, verbose_name="Extra Info")

    creator = ForeignKey(to='users.User', related_name='stock_creator', on_delete=SET_NULL, db_column='Creator', blank=True, null=True)

    time_created = DateTimeField(db_column='TimeCreated', auto_created=True, default=timezone.now, blank=True, null=True)

    time_modified = DateTimeField(db_column='TimeModified', auto_now=True, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'stock'

        verbose_name = 'Stock'
        verbose_name_plural = 'Stocks'

        ordering = ['name']

    def save(self, *args, **kwargs):
        super(Stock, self).save(*args, **kwargs)

    def __str__(self):
        return '[{}] -  {}'.format(self.symbol, self.name)

    def get_absolute_url(self):
        return reverse("accounts:detail", kwargs={"pk": self.pk})

market/forms.py
from django import forms

from market.models import Stock


class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = '__all__'

market/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from market.forms import *


@login_required
def create_stock(request):
    if request.method == 'POST':
        created_stock_pk = None
        filled_form = StockForm(request.POST)
        if filled_form.is_valid():
            created_stock = filled_form.save()
            created_stock_pk = created_stock.pk
            note = 'stock %s was created' % (filled_form.cleaned_data['name'])
            filled_form = StockForm()
        else:
            note = 'stock was not created, please try again'
        new_form = StockForm()

        return render(request, 'market/add_stock.html',
                      {'StockForm': filled_form, 'note': note, 'created_stock_pk': created_stock_pk})
        # return redirect('market:list_stocks')
    else:
        form = StockForm()
        return render(request, 'market/add_stock.html', {'StockForm': form})


@login_required
def update_stock(request, pk):
    stock = Stock.objects.get(pk=pk)
    form = StockForm(instance=stock)
    if request.method == 'POST':
        filled_form = StockForm(request.POST, instance=stock)
        if filled_form.is_valid():
            filled_form.save()
            form = filled_form
            note = 'Your stock has been processed.'
            return render(request, 'market/edit_stock.html', {'StockForm': form, 'stock': stock, 'note': note})
            # return redirect('market:list_stocks')
    return render(request, 'market/edit_stock.html', {'StockForm': form, 'stock': stock})


@login_required
def view_stock(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    return render(request, 'market/view_stock.html', {'stock': stock})


@login_required
def list_stocks(request):
    stocks = Stock.objects.get_queryset().exclude(symbol='')
    return render(request, 'market/list_stocks.html', {'stocks': stocks})


@login_required
def delete_stock(request, pk):
    stock = Stock.objects.get(pk=pk)
    stock.delete()
    return redirect('market:list_stocks')


####################################################################################################################
####################################################################################################################
@login_required
def view_stock_weekly(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    return render(request, 'market/view_stock_weekly.html', {'stock': stock})


@login_required
def view_stock_monthly(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    return render(request, 'market/view_stock_monthly.html', {'stock': stock})


@login_required
def sectors(request):
    return render(request, 'market/sector_performances.html')

templates/market/add_stock.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Add Stock{% endblock %}

{% block top_heading %}
    {% if created_stock_pk %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i> {{ note }} </h4>
            <h2><a href="{% url 'market:update_stock' created_stock_pk %}">Edit Stock</a></h2>
            <h6><a href="{% url 'market:list_stocks' %}">Stocks</a></h6>
        </div>
    {% endif %}

{% endblock top_heading %}


{% block card_header %}Add Stock{% endblock card_header %}

{% block card-body %}
    <form class="form-horizontal" action="{% url 'market:create_stock' %}" method="post">
        {% csrf_token %}

        <div class="form-group">
            <label for="first_name" class="control-label">Symbol</label>
            <div>
                {% render_field StockForm.symbol type="text" class="form-control" id="Symbol" placeholder="Symbol" %}
            </div>
        </div>

        <div class="form-group">
            <label for="first_name" class="control-label">Name</label>
            <div>
                {% render_field StockForm.name type="text" class="form-control" id="name" placeholder="Co. Name" %}
            </div>
        </div>

        <div class="form-group">
            <label for="first_name" class="control-label">Sector</label>
            <div>
                {% render_field StockForm.sector type="text" class="form-control" id="sector" placeholder="Sector Name" %}
            </div>
        </div>

        <div class="form-group">
            <label for="first_name" class="control-label">Info</label>
            <div>
                {% render_field StockForm.info type="text" class="form-control" id="info" placeholder="Extra .." %}
            </div>
        </div>

        <button class="btn btn-primary" type="submit">
            <i class="fas fa-plus"></i>
        </button>

    </form>
{% endblock card-body %}

templates/market/edit_stock.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block top_heading %}
    {% if note %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-check"></i> {{ note }} </h4>
            <h2><a href="{% url 'market:view_stock' stock.pk %}">Show Stock</a></h2>
        </div>
    {% endif %}
{% endblock top_heading %}

{% block title %}Update Stock{% endblock %}

{% block card_header %}Update Stock{% endblock card_header %}

{% block card-body %}
    <form class="form-horizontal" action="{% url 'market:update_stock' stock.pk %}" method="post">
        {% csrf_token %}

        <div class="form-group">
            <label for="first_name" class="control-label">Symbol</label>
            <div>
                {% render_field StockForm.symbol type="text" class="form-control" id="Symbol" placeholder="Symbol" %}
            </div>
        </div>

        <div class="form-group">
            <label for="first_name" class="control-label">Name</label>
            <div>
                {% render_field StockForm.name type="text" class="form-control" id="name" placeholder="Co. Name" %}
            </div>
        </div>

        <div class="form-group">
            <label for="first_name" class="control-label">Sector</label>
            <div>
                {% render_field StockForm.sector type="text" class="form-control" id="sector" placeholder="Sector Name" %}
            </div>
        </div>

        <div class="form-group">
            <label for="first_name" class="control-label">Info</label>
            <div>
                {% render_field StockForm.info type="text" class="form-control" id="info" placeholder="Extra .." %}
            </div>
        </div>

        <a href="{% url 'market:list_stocks' %}" class="btn btn-danger">Cancel</a>

        <button class="btn btn-primary" type="submit">
            <i class="fas fa-edit"></i>
        </button>

    </form>
{% endblock card-body %}

templates/market/list_stocks.html
{% extends "base.html" %}

{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.css">
{% endblock extra_css %}

{% block title %}list Stocks{% endblock %}

{% block heading %}
    <!--Card content-->
    <div class="card-body d-sm-flex justify-content-between">

        <h4 class="mb-2 mb-sm-0 pt-1">
            <span>Add New Stock</span>
        </h4>

        <form class="d-flex justify-content-center">
            <a href="{% url 'market:create_stock' %}" class="btn btn-primary">
                <i class="fas fa-plus"></i>
            </a>
        </form>

    </div>
{% endblock heading %}

{% block card_header %}Stocks{% endblock card_header %}

{% block card-body %}

    <table id="table" data-toggle="table" data-pagination="true"
           data-search="true" data-show-columns="true"
           data-show-toggle="true" data-resizable="true" data-toolbar="#toolbar">
        <thead>
        <tr>
            <th data-field="id">Pk</th>
            <th data-field="symbol" data-editable="true">Symbol</th>
            <th data-field="name" data-editable="true">Name</th>
            <th data-field="sector">Sector</th>
            <th data-field="action">Actions</th>
        </tr>
        </thead>

        <tbody>

        {% for stock in stocks %}

            <tr>
                <td>{{ stock.pk }}</td>
                <td>{{ stock.symbol }}</td>
                <td>{{ stock.name }}</td>
                <td>{{ stock.sector }}</td>

                <td class="datatable-ct">
                    <a href="{% url 'market:update_stock' stock.pk %}"><i class="fa fa-edit"></i></a>
                    <a href="{% url 'market:delete_stock' stock.pk %}"><i class="fa fa-trash"></i></a>
                    <a href="{% url 'market:view_stock' stock.pk %}"><i class="fa fa-eye"></i></a>
                </td>
            </tr>

        {% endfor %}


        </tbody>
    </table>

{% endblock card-body %}

{% block script %}
        <script src="https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.js"></script>
{% endblock script %}

templates/market/sector_performances.html
{% extends "base.html" %}

{% block title %}Sectors{% endblock %}

{% block heading %}

    <h4 class="mb-2 mb-sm-0 pt-1" id="xoxo">
        <span>Wait a Sec..</span>
    </h4>

{% endblock heading %}

{% block row %}

    <!--Grid column-->
    <div class="col-md-12 mb-4">
        {% block col %}

            <table class="table table-hover md-sm-10">
                <!-- Table head -->
                <thead class="rgba-green-light lighten-4">
                <tr>
                    <th>Rank</th>
                    <th>Real Estate</th>
                    <th>Utilities</th>
                    <th>Consumer Staples</th>
                    <th>Communication Services</th>
                    <th>Health Care</th>
                    <th>Energy</th>
                    <th>Industrials</th>
                    <th>Information Technology</th>
                    <th>Consumer Discretionary</th>
                    <th>Financials</th>
                    <th>Materials</th>
                </tr>
                </thead>
                <!-- Table head -->

                <!-- Table body -->
                <tbody id="sectorx">

                </tbody>
                <!-- Table body -->
            </table>
            <!-- Table  -->

        {% endblock col %}
    </div>
    <!--Grid column-->
{% endblock row %}


{% block script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.15.4/bootstrap-table.min.js"></script>

    <script>
        $(document).ready(function () {

            $.ajax({
                url: "{% url 'market_api:SectorPerformances'%}",
                dataType: 'json',
                contentType: "application/json",
                success: function (data) {
                    console.log(data);

                    for (let rank in data) {
                        let performance_info = data[rank];
                        let tr_str =
                            '<tr>' +
                            '<td scope="row" style="background-color: #9a9b9a">' + rank + '</td>' +
                            '<td>' + Number(performance_info["Real Estate"]).toFixed(4) + '</td>' +
                            '<td>' + Number(performance_info["Utilities"]).toFixed(4) + '</td>' +
                            '<td>' + Number(performance_info["Consumer Staples"]).toFixed(4) + '</td>' +
                            '<td>' + Number(performance_info["Communication Services"]).toFixed(4) + '</td>' +
                            '<td>' + Number(performance_info["Health Care"]).toFixed(4) + '</td>' +
                            '<td>' + Number(performance_info["Energy"]).toFixed(4) + '</td>' +
                            '<td>' + Number(performance_info["Industrials"]).toFixed(4) + '</td>' +
                            '<td>' + Number(performance_info["Information Technology"]).toFixed(4) + '</td>' +
                            '<td>' + Number(performance_info["Consumer Discretionary"]).toFixed(4) + '</td>' +
                            '<td>' + Number(performance_info["Financials"]).toFixed(4) + '</td>' +
                            '<td>' + Number(performance_info["Materials"]).toFixed(4) + '</td>' +
                            '</tr>';

                        $("#sectorx").append(tr_str);


                    }

                }

            })

        });

        setTimeout(function () {
            $('#xoxo').hide();
        }, 4000); // <-- time in milliseconds


    </script>
{% endblock script %}

templates/market/view_stock_monthly.html
{% extends "base.html" %}

{% load static %}

{% block title %}Stock Monthly{% endblock %}


{% block top_heading %}
    <div class="col-md-9 mb-4">

        <div class="card mb-4">
            <div class="card-body" id="xoxo">
                <h5 class="mb-2 mb-sm-0 pt-1">
                    <span style="color: greenyellow">Please wait while data is loading ..</span>
                </h5>
            </div>
        </div>

        <div class="card mb-4">
            <div class="card-body">
                <div class="card-body d-sm-flex justify-content-between">

                    <a href="{% url 'market:view_stock' stock.pk %}" class="btn btn-green">
                        <i class="fas fa-backward"></i> Back
                    </a>

                    <a href="{% url 'market:view_stock_weekly' stock.pk %}" class="btn btn-black">
                        <i class="fas fa-business-time"></i> Stock Monthly
                    </a>

                </div>
            </div>
        </div>

    </div>

{% endblock top_heading %}


{% block row %}
    <!--Grid column-->
    <div class="col-md-9 mb-4">

        <!--Card-->
        <div class="card mb-4">

            <!-- Card header -->
            <div class="card-header text-center">
                Chart
            </div>

            <!--Card content-->
            <div class="card-body">

                <canvas id="Chart"></canvas>

            </div>

        </div>
        <!--/.Card-->

        <!--Card-->
        <div class="card mb-4">

            <!-- Card header -->
            <div class="card-header text-center">
                Time Series Monthly
            </div>

            <!--Card content-->
            <div class="card-body">

                <!-- Table  -->
                <table class="table table-hover">
                    <!-- Table head -->
                    <thead class="blue-gradient-rgba lighten-4">
                    <tr>
                        <th>Date</th>
                        <th>Open</th>
                        <th>High</th>
                        <th>Low</th>
                        <th>Close</th>
                        <th>Volume</th>

                    </tr>
                    </thead>
                    <!-- Table head -->

                    <!-- Table body -->
                    <tbody id="timeseries">

                    </tbody>
                    <!-- Table body -->
                </table>
                <!-- Table  -->

            </div>

        </div>
        <!--/.Card-->

    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-md-3 mb-4">

        <!--Card-->
        <div class="card mb-4">

            <!--Card content-->
            <div class="card-body">

                <!-- List group links -->
                <div class="list-group list-group-flush" id="info">
                    <a class="list-group-item list-group-item-action waves-effect">{{ stock.name }}
                    </a>
                    <a class="list-group-item list-group-item-action waves-effect">
                        <span class="badge badge-primary badge-pill pull-right">{{ stock.symbol }}</span>
                    </a>
                    <a class="list-group-item list-group-item-action waves-effect">
                        <span class="badge badge-warning badge-pill pull-right">{{ stock.sector }}</span>
                    </a>
                </div>
                <!-- List group links -->

            </div>

        </div>
        <!--/.Card-->

    </div>
    <!--Grid column-->

{% endblock row %}

{% block script %}
    <script type="text/javascript" src="{% static 'js/modules/chart.js' %}"></script>

    <script>
        $(document).ready(function () {

            $.ajax({
                url: "{% url 'market_api:StockQuote' stock.pk %}",
                type: "get",
                dataType: 'json',
                success: function (response) {
                    console.log(response);
                    // response is form in html format
                    let symbol = response["01. symbol"];
                    let open = response["02. open"];
                    let high = response["03. high"];
                    let low = response["04. low"];
                    let price = response["05. price"];
                    let volume = response["06. volume"];
                    let latest = response["07. latest trading day"];
                    let close = response["08. previous close"];
                    let change = response["09. change"];
                    let change_percent = response["10. change percent"];


                    let str =
                        '<a class="list-group-item list-group-item-action waves-effect" style="color: #0b2e13"> High: ' +
                        '<span class="badge badge-success badge-pill pull-right">' + high + ' ' +
                        '<i class="fas fa-arrow-up ml-1"></i>' +
                        '</span>' +
                        '</a>' +

                        '<a class="list-group-item list-group-item-action waves-effect" style="color: #9f105c"> Low: ' +
                        '<span class="badge badge-danger badge-pill pull-right">' + low + ' ' +
                        '<i class="fas fa-arrow-down ml-1"></i>' +
                        '</span>' +
                        '</a>' +

                        '<a class="list-group-item list-group-item-action waves-effect" style="color: #0b2e13"> Open: ' +
                        open +
                        '</a>' +

                        '<a class="list-group-item list-group-item-action waves-effect" style="color: #b21f2d"> Close: ' +
                        close +
                        '</a>' +

                        '<a class="list-group-item list-group-item-action waves-effect" style="color: #1b451d"> Price: ' +
                        price +
                        '</a>' +

                        '<a class="list-group-item list-group-item-action waves-effect" style="color: #2c0419"> Volume: ' +
                        volume +
                        '</a>' +

                        '<a class="list-group-item list-group-item-action waves-effect" style="color: #5b32bc"> Latest trading day: ' +
                        latest +
                        '</a>' +

                        '<a class="list-group-item list-group-item-action waves-effect"> Change: ' +
                        change +
                        '</a>' +

                        '<a class="list-group-item list-group-item-action waves-effect"> Change %: ' +
                        change_percent +
                        '</a>'
                    ;

                    $("#info").append(str);
                }
            });

            ///////////////////////////////////////////////////////////////////////////////

            $.ajax({
                url: "{% url 'market_api:TimeSeriesMonthly' stock.pk %}",
                dataType: 'json',
                contentType: "application/json",
                success: function (data) {
                    console.log(data);

                    let dates = [];
                    let volume = [];

                    for (let time in data) {
                        let time_info = data[time];
                        let tr_str =
                            '<tr>' +
                            '<td scope="row">' + time + '</td>' +
                            '<td>' + Number(time_info["1. open"]) + '</td>' +
                            '<td>' + Number(time_info["2. high"]) + '</td>' +
                            '<td>' + Number(time_info["3. low"]) + '</td>' +
                            '<td>' + Number(time_info["4. close"]) + '</td>' +
                            '<td>' + Number(time_info["5. volume"]) + '</td>' +
                            '</tr>';

                        $("#timeseries").append(tr_str);

                        // Fill lists
                        dates.push(time);
                        volume.push(Number(time_info["5. volume"]));

                    }

                    //.......................... Chart ....................................................

                    let ctx = document.getElementById("Chart").getContext('2d');
                    let myChart = new Chart(ctx, {
                        type: 'bar',
                        data: data = {
                            labels: [dates[0], dates[1], dates[2], dates[3], dates[4], dates[5], dates[6],
                                dates[7], dates[8], dates[9], dates[10], dates[11]],
                            datasets: [
                                {
                                    label: 'Volume',
                                    yAxisID: 'y-axis-b',
                                    data: [volume[0], volume[1], volume[2], volume[3], volume[4], volume[5], volume[6],
                                        volume[7], volume[8], volume[9], volume[10], volume[11]],
                                    barPercentage: '1',
                                    categoryPercentage: '1',
                                    backgroundColor: 'rgb(29, 41, 57)',
                                    borderColor: 'rgb(29, 41, 57)',
                                    borderWidth: '1',
                                    borderSkipped: 'bottom',
                                    hoverBackgroundColor: 'rgb(29, 41, 57)',
                                    hoverBorderColor: 'rgb(29, 41, 57)',
                                    hoverBorderWidth: '3',
                                },
                            ]
                        },
                        options: {
                            title: {
                                display: true,
                                text: 'Stock Volumes - Last Year',
                                fontSize: '20',
                                fontFamily: 'Open Sans, sans-serif',
                                // fontColor
                                // fontStyle
                                // padding
                                // lineHeight
                            },
                            scales: {
                                xAxes: [{
                                    ticks: {
                                        min: 0
                                    }
                                }],
                                yAxes: [{
                                    position: "left",
                                    id: "y-axis-a",
                                }, {
                                    position: "right",
                                    id: "y-axis-b",
                                }]
                            }
                        }
                    });

                    //................................................................................

                }
            })
            /////////////////////////////////////////////////////////////////////////////////

        });


        setTimeout(function () {
            $('#xoxo').hide();
        }, 5000); // <-- time in milliseconds


    </script>

{% endblock script %}