StocksScreener/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from schema_graph.views import Schema

admin.autodiscover()

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("users/api/v1/", include("users.api_urls", namespace="users_api")),
    path("market/", include("market.urls", namespace="market")),
    path("market/api/v1/", include("market.api_urls", namespace="market_api")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("egx/", include("egx.urls", namespace="egx")),
    path("crypto/", include("crypto.urls", namespace="crypto")),
    path("forex/", include("forex.urls", namespace="forex")),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("StocksScreener.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

urlpatterns += [
    path("schema/", Schema.as_view()),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
######################################################################
admin.site.site_header = "Stocks-Screener"
admin.site.site_title = "Stocks Screener"
admin.site.index_title = "Stocks Screener Admin"
#######################################################################

egx/urls.py
from django.urls import path

from egx.views import home, companies

app_name = "egx"

urlpatterns = [
    path('', home, name='home'),
    path('companies', companies, name='companies'),
]

egx/models.py
# Create your models here.

egx/views.py
import requests
from django.shortcuts import render


def home(request):
    response = requests.get('https://www.mubasher.info/api/1/stocks/prices/all?country=eg')
    data = response.json()
    print(data)
    return render(request, 'egx/home.html', {'lastUpdate': data['lastUpdate'], 'prices': data['prices']})


def companies(request):
    response = requests.get('https://www.mubasher.info/api/1/listed-companies?country=eg&size=400')
    data = response.json()
    print(data['rows'])
    return render(request, 'egx/companies.html', {'companies': data['rows']})

templates/egx/companies.html
{% extends "base.html" %}

{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.css">
{% endblock extra_css %}

{% block title %}EGX companies{% endblock %}

{% block heading %}
{% endblock heading %}

{% block card_header %} الشركـات المدرجـة بالبـــورصة المصريــة {% endblock card_header %}

{% block card-body %}

    <table id="table" data-toggle="table" data-pagination="true"
           data-search="true" data-show-columns="true"
           data-show-toggle="true" data-resizable="true" data-toolbar="#toolbar" class="rtl">
        <thead>
        <tr>

            <th data-field="code">الرمز</th>
            <th data-field="price">السعر</th>
            <th data-field="sector">القطاع</th>
            <th data-field="name">السهم</th>

        </tr>
        </thead>

        <tbody>

        {% for company in companies %}
            <tr>
                <td>{{ company.symbol }}</td>
                <td>{{ company.price }}</td>
                <td>{{ company.sector }}</td>
                <td>{{ company.name }}</td>
            </tr>

        {% endfor %}


        </tbody>
    </table>

{% endblock card-body %}

{% block script %}
    <script src="https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.js"></script>
{% endblock script %}

templates/egx/home.html
{% extends "base.html" %}

{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.css">
{% endblock extra_css %}

{% block title %}EGX Stocks{% endblock %}

{% block heading %}
    <!--Card content-->
    <div class="card-body d-sm-flex justify-content-between">

        <h4 class="mb-2 mb-sm-0 pt-1">
            <span class="danger-color"> Last Update:</span>
            <span class="info-color">{{ lastUpdate }}</span>
        </h4>

        <h5>
            <a class="btn btn-black waves-effect waves-light" href="{% url 'egx:companies' %}" target="_blank">EGX
                Companies</a>
        </h5>

    </div>
{% endblock heading %}

{% block card_header %} EGX {% endblock card_header %}

{% block card-body %}

    <table id="table" data-toggle="table" data-pagination="true"
           data-search="true" data-show-columns="true"
           data-show-toggle="true" data-resizable="true" data-toolbar="#toolbar">
        <thead>
        <tr>

            <th data-field="code">الرمز</th>
            <th data-field="value" data-editable="true">آخر سعر</th>
            <th data-field="change" data-editable="true">التغير</th>
            <th data-field="changePercentage">نسبة التغير</th>
            <th data-field="turnover">القيمة</th>
            <th data-field="volume">الكمية</th>
            <th data-field="open">سعر الفتح</th>
            <th data-field="high">أعلى سعر</th>
            <th data-field="low">أقل سعر</th>
            <th data-field="updatedAt">آخر تحديث</th>
            <th data-field="name">السهم</th>

        </tr>
        </thead>

        <tbody>

        {% for price in prices %}

            <tr>
                <td>{{ price.code }}</td>
                <td>{{ price.value }}</td>
                {% if price.status == 'up' %}
                    <td class="success-color">{{ price.change }}</td>
                {% else %}
                    <td class="danger-color">{{ price.change }}</td>
                {% endif %}
                <td>{{ price.changePercentage }}</td>
                <td>{{ price.turnover }}</td>
                <td>{{ price.volume }}</td>
                <td>{{ price.open }}</td>
                <td>{{ price.high }}</td>
                <td>{{ price.low }}</td>
                <td>{{ price.updatedAt }}</td>
                <td>{{ price.name }}</td>
            </tr>

        {% endfor %}


        </tbody>
    </table>

{% endblock card-body %}

{% block script %}
    <script src="https://unpkg.com/bootstrap-table@1.15.5/dist/bootstrap-table.min.js"></script>
{% endblock script %}