StocksScreener/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from schema_graph.views import Schema

admin.autodiscover()

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("users/api/v1/", include("users.api_urls", namespace="users_api")),
    path("market/", include("market.urls", namespace="market")),
    path("market/api/v1/", include("market.api_urls", namespace="market_api")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("egx/", include("egx.urls", namespace="egx")),
    path("crypto/", include("crypto.urls", namespace="crypto")),
    path("forex/", include("forex.urls", namespace="forex")),
]

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("StocksScreener.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
]

urlpatterns += [
    path("schema/", Schema.as_view()),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
######################################################################
admin.site.site_header = "Stocks-Screener"
admin.site.site_title = "Stocks Screener"
admin.site.index_title = "Stocks Screener Admin"
#######################################################################

egx/urls.py
from django.urls import path

from egx.views import home, companies

app_name = "egx"

urlpatterns = [
    path('', home, name='home'),
    path('companies', companies, name='companies'),
]

market/urls.py
from django.urls import path

from market.views import *

app_name = "market"

urlpatterns = [
    path('list', list_stocks, name='list_stocks'),
    path('create', create_stock, name='create_stock'),
    path('update/<int:pk>', update_stock, name='update_stock'),
    path('delete/<int:pk>', delete_stock, name='delete_stock'),
    path('<int:pk>', view_stock, name='view_stock'),

    path('stock_weekly/<int:pk>', view_stock_weekly, name='view_stock_weekly'),
    path('stock_monthly/<int:pk>', view_stock_monthly, name='view_stock_monthly'),

    path('sectors', sectors, name='sectors'),

]

users/urls.py
from django.urls import path

from .views import *

app_name = "users"

urlpatterns = [
    path("", view=user_redirect_view, name="redirect"),
    path("update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">

    <!-- Your custom styles (optional) -->
    {#    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">#}


    {% block extra_css %}
    {% endblock extra_css %}
</head>

<body class="grey lighten-3">

<!--Main Navigation-->
<header>

    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
        <div class="container-fluid">

            <!-- Brand -->
            <a class="navbar-brand waves-effect" href="http://shokr.works" target="_blank">
                <strong class="blue-text">Shokr</strong>
            </a>

            <!-- Collapse -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!-- Left -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'home' %}">Home
                            {#                            <span class="sr-only">(current)</span>#}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'market:list_stocks' %}" target="_self">Market</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'market:sectors' %}" target="_blank">Sectors</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'crypto:home' %}"> Crypto</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'forex:home' %}"> Forex</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'egx:home' %}" target="_blank">EGX</a>
                    </li>

                    <li class="nav-item">
                        {% if request.user.pk %}
                            <a class="nav-link waves-effect"
                               href="{% url 'users:redirect' %}">{{ request.user }}</a>

                            <li class="nav-item">
                                <a href="{% url 'logout' %}" class="nav-link waves-effect">
                                    logout
                                </a>
                            </li>
                        {% else %}
                            <a class="nav-link waves-effect"
                               href="{% url 'login' %}">
                                Login
                            </a>
                        {% endif %}
                    </li>
                </ul>

                <!-- Right -->
                <ul class="navbar-nav nav-flex-icons">
                    <li class="nav-item">
                        <a href="https://www.linkedin.com/in/muhammedshokr/" class="nav-link waves-effect"
                           target="_blank">
                            <i class="fab fa-linkedin"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://twitter.com/MuhammedShokr" class="nav-link waves-effect" target="_blank">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://github.com/Shokr/Stocks-Screener"
                           class="nav-link border border-light rounded waves-effect"
                           target="_blank">
                            <i class="fab fa-github"></i>
                        </a>
                    </li>
                </ul>

            </div>

        </div>
    </nav>
    <!-- Navbar -->

    <!-- Sidebar -->
    {#    <div class="sidebar-fixed position-fixed">#}
    {##}
    {#        <a class="logo-wrapper waves-effect">#}
    {#            <img src="https://mdbootstrap.com/img/logo/mdb-email.png" class="img-fluid" alt="">#}
    {#        </a>#}
    {##}
    {#        <div class="list-group list-group-flush">#}
    {#            <a href="#" class="list-group-item active waves-effect">#}
    {#                <i class="fas fa-chart-pie mr-3"></i>Dashboard#}
    {#            </a>#}
    {#            <a href="#" class="list-group-item list-group-item-action waves-effect">#}
    {#                <i class="fas fa-user mr-3"></i>Profile</a>#}
    {#            <a href="#" class="list-group-item list-group-item-action waves-effect">#}
    {#                <i class="fas fa-table mr-3"></i>Tables</a>#}
    {#            <a href="#" class="list-group-item list-group-item-action waves-effect">#}
    {#                <i class="fas fa-map mr-3"></i>Maps</a>#}
    {#            <a href="#" class="list-group-item list-group-item-action waves-effect">#}
    {#                <i class="fas fa-money-bill-alt mr-3"></i>Orders</a>#}
    {#        </div>#}
    {##}
    {#    </div>#}
    <!-- Sidebar -->

</header>
<!--Main Navigation-->

<!--Main layout-->
<main class="pt-5 mx-lg-12">
    <div class="container-fluid mt-5">

        {% block top_heading %}

            <!-- Heading -->
            <div class="card mb-4 wow fadeIn">
                {% block heading %}
                {% endblock heading %}
            </div>
            <!-- Heading -->
        {% endblock top_heading %}

        <!--Grid row-->
        <div class="row wow fadeIn">
            {% block row %}

                <!--Grid column-->
                <div class="col-md-12 mb-4">
                    {% block col %}

                        <!--Card-->
                        <div class="card">

                            <!-- Card header -->
                            <div class="card-header">{% block card_header %}Hello{% endblock card_header %}</div>

                            <!--Card content-->
                            <div class="card-body">
                                {% block card-body %}

                                {% endblock card-body %}
                            </div>

                        </div>
                        <!--/.Card-->
                    {% endblock col %}
                </div>
                <!--Grid column-->
            {% endblock row %}

        </div>
        <!--Grid row-->

    </div>
</main>
<!--Main layout-->


<!--Footer-->
{#<footer class="page-footer text-center font-small primary-color-dark darken-2 mt-4 wow fadeIn">#}
{#    #}
{#    <!--Copyright-->#}
{#    <div class="footer-copyright py-3">#}
{#        © 2020 Copyright:#}
{#        <a href="http://shokr.works" target="_blank"> shokr.works </a>#}
{#    </div>#}
{#    <!--/.Copyright-->#}
{##}
{#</footer>#}
<!--/.Footer-->

<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
    // Animations initialization
    new WOW().init();
</script>

{% block script %}
{% endblock script %}

<script data-mode="hash" async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
<noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt=""/></noscript>
</body>
</html>